#ifndef MK1MF_BUILD
    /* auto-generated by util/mkbuildinf.pl for crypto/cversion.c */
    #define CFLAGS cflags
    /*
     * Generate CFLAGS as an array of individual characters. This is a
     * workaround for the situation where CFLAGS gets too long for a C90 string
     * literal
     */
    static const char cflags[] = {
        'c','o','m','p','i','l','e','r',':',' ','a','r','m','v','5','-','l','i',
        'n','u','x','-','g','c','c',' ','-','I','.',' ','-','I','.','.',' ','-',
        'I','.','.','/','i','n','c','l','u','d','e',' ',' ','-','O','\0'
    };
    #define PLATFORM "platform: dist"
    #define DATE "built on: Wed Sep 30 11:55:29 2015"
#endif
