#! /bin/sh

[ -f /etc/banner ] && cat /etc/banner

CMDLINE=`cat /proc/cmdline`
for x in $CMDLINE; do
	case $x in
                model=*)
                        MODEL="${x#model=}"
                ;;

                devid=*)
                        SN="${x#devid=}"
                ;;
        esac
done

LD_LIBRARY_PATH=/lib:/usr/local/lib
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
SHELL=/bin/ash
TMOUT=300

export PATH LD_LIBRARY_PATH MODEL SN
