#!/bin/sh /etc/rc.common

START=97
STOP=97 

start() {
	/opt/thingplus-gateway/thingplus.sh start
}

stop() {
	/opt/thingplus-gateway/thingplus.sh stop
}

status() {
	/opt/thingplus-gateway/thingplus.sh status
}
