#!/bin/sh /etc/rc.common

BOOT=10
STOP=98

system_config() {
    local cfg="$1"

    local hostname conloglevel timezone

    config_get hostname "$cfg" hostname 'FTM-50S'
    echo "$hostname" > /proc/sys/kernel/hostname

    config_get conloglevel "$cfg" conloglevel
    config_get buffersize "$cfg" buffersize
    [ -z "$conloglevel" -a -z "$buffersize" ] || dmesg ${conloglevel:+-n $conloglevel} ${buffersize:+-s $buffersize}
    
    config_get timezone "$cfg" timezone 'UTC'
    echo "$timezone" > /tmp/TZ

    if [ -x /sbin/syslogd ]; then
        local log_ip log_size log_port log_type log_file
        config_get log_ip "$cfg" log_ip 
        config_get log_size "$cfg" log_size 16
        config_get log_port "$cfg" log_port 514 
        config_get log_type "$cfg" log_type circular
        config_get log_file "$cfg" log_file "/var/log/messages"
        if [ "$log_type" = "file" ]; then
            syslogd -s $log_size -O $log_file ${log_ip:+-L -R ${log_ip}:${log_port}} -S
        else
            syslogd -C${log_size} ${log_ip:+-L -R ${log_ip}:${log_port}}
        fi  
    fi  
    config_get klogconloglevel "$cfg" klogconloglevel
    [ -x /sbin/klogd ] && klogd ${klogconloglevel:+-c $klogconloglevel}
}

apply_uci_config() {
    sh -c '. /etc/functions.sh; include /lib/config; uci_apply_defaults'
}

start() {
	if [ ! -d /proc ]; then
		mkdir /proc	
	fi
	mounting "/proc" proc /proc 1

	if [ ! -d /sys ]; then
		mkdir /sys
	fi
	mounting "/sys" sysfs sysfs 1

	if [ ! -d /dev ]; then
		mkdir /dev
	fi
	mounting "/dev" tmpfs mdev  1

	if [ ! -d /dev/pts ]; then
		mkdir /dev/pts
	fi
	mounting "/dev/pts" devpts devpts 0

	if [ ! -d /var ]; then
		mkdir /var 
	fi
	mounting "/var" tmpfs tmpfs 0
	if [ $? -eq 0 ]; then
		mkdir /var/log
		mkdir /var/lock
		mkdir /var/run
		mkdir /var/spool
	fi

 	grep -q debugfs /proc/filesystems && mount -t debugfs debugfs /sys/kernel/debug

    	apply_uci_config
    	config_load system
    	config_foreach system_config system
	
	#   ---------------------------------------------
	#   MDEV Support
	#   (Requires sysfs support in the kernel)
	#   ---------------------------------------------
	
	echo -n " Populating devices            : "
	mkdir /dev/input
	mkdir /dev/snd
	mdev -s
	status_out $? 0
	
	#   ---------------------------------------------
	#   Mount User Space
	#   ---------------------------------------------
	if [ ! -d /mnt ]; then
		mkdir /mnt
	fi
	mounting "/mnt" tmpfs tmpfs 0
	
	cat /proc/mtd | grep User >& /dev/null
	if [ $? -eq 0 ] ; then
		if [ ! -d /mnt/data ]; then
			mkdir -p /mnt/data
		fi

		echo "/mnt/data" | awk '{ printf(" Mounting %-20s : ", $1)}'
		MTDBLOCK=`cat /proc/mtd | grep "User" | awk '{ print $1 }' | sed -e 's/mtd//' -e 's/://' | awk '{ print "mtdblock" $1 }'`
		
		mount -t jffs2 /dev/$MTDBLOCK /mnt/data >& /dev/null
		if [ $? -eq 0 ] ; then
			echo "[SUCCESS]"
		else
			rmdir /mnt/data
			echo "[FAILED]"
		fi
	fi
	
	
	#   ---------------------------------------------
	#   fstab support
	#   ---------------------------------------------
	echo "fstab" | awk '{ printf(" Mounting %-20s : ", $1)}'
	mount -a
	status_out $? 0

	echo -n " Enabling hot-plug             : "
	echo "/sbin/mdev" > /proc/sys/kernel/hotplug
	status_out $? 0

	echo -n " Populating devices            : "
	mdev -s
	status_out $? 0
}

stop() {
        killall -9 syslogd 2> /dev/null
}

