#!/bin/sh /etc/rc.common

START=91

start() {
	/usr/sbin/httpd -h /www 2> /dev/null
}

stop() {
	pkill httpd 2> /dev/null
}

status() {
	if pidof httpd | sed "s/$$\$//" | grep -q [0-9]
	then
		echo "running"
	else
		echo "stopped"
	fi
}
