#!/bin/sh /etc/rc.common

START=50
STOP=50

start() {
	echo Starting firewall: iptables.
	iptables-restore < /etc/iptables.conf
}

save() {
	iptables-save > /etc/iptables.conf
}

stop() {
	echo Stopping firewall: iptables.
	iptables-restore < /etc/iptables.allow
}

