#!/bin/sh /etc/rc.common
#
# start/stop networking daemons.
#
# chkconfig: S 40 90
#
START=40

PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"

[ -x /sbin/ifup ] || exit 0

process_options() {
    [ -e /etc/network/options ] || return 0
}

check_network_file_systems() {
    [ -e /proc/mounts ] || return 0

    exec 9<&0 < /proc/mounts
    while read DEV MTPT FSTYPE REST; do
	case $DEV in
	/dev/nbd*|/dev/nd[a-z]*|/dev/etherd/e*)
	    echo "not deconfiguring network interfaces: network devices still mounted."
	    exit 0
	    ;;
	esac
	case $FSTYPE in
	nfs|nfs4|smbfs|ncp|ncpfs|cifs|coda|ocfs2|gfs|pvfs|pvfs2|fuse.httpfs|fuse.curlftpfs)
	    echo "not deconfiguring network interfaces: network file systems still mounted."
	    exit 0
	    ;;
	esac
    done
    exec 0<&9 9<&-
}

start() {
	process_options

	echo -n "Configuring network interfaces: "
	/sbin/ifup -a
        echo "done."
}

stop() {
	check_network_file_systems

	echo -n  "Deconfiguring network interfaces: "
	/sbin/ifdown -a
	echo "done."
}

restart() {
	process_options

	echo -n "Reconfiguring network interfaces: "
	/sbin/ifdown -a
	/sbin/ifup -a
	echo "done."
}

