#!/bin/sh /etc/rc.common

START=60

NTPD=`which ntpd`
CONF_LINK_FILE="/etc/ntp.conf"
CONF_FILE="/tmp/ntp.conf"

check_server() {
        local hostname
        local port

        config_get hostname $1 hostname
        config_get port $1 port

        [ -z "$hostname" ] && return

        echo "server $hostname" >> $CONF_FILE
}


start() {
        NTPD_RUNNING=`ps  | grep $NTPD | grep -v grep`
        if [ -n "$NTPD_RUNNING" ] ; then
		logger alrelay running
	fi

	CONF_EXIST=`readlink $CONF_LINK_FILE`

	if [ -z "$CONF_EXIST" ] ; then
		ln -sf $CONF_FILE $CONF_LINK_FILE	
	fi 

        config_load ntpd
        echo "" > $CONF_FILE
        config_foreach check_server ntpserver

        logger starting ntpd
        ntpd 2> /dev/null
}

stop() {
        logger stopping ntpd
        killall ntpd

	rm -f $CONF_FILE
}
