#!/bin/sh /etc/rc.common

START=70

start() {
	if ! pidof udhcpd | sed "s/$$\$//" | grep -q [0-9]
	then
		if [ ! -f /var/lib/misc/udhcpd.leases ]; then
			
			if [ ! -d /var/lib/misc ]; then
				mkdir -p /var/lib/misc
			fi

			echo "" > /var/lib/misc/udhcpd.leases
		fi

		/sbin/udhcpd /etc/config/udhcpd &
	fi	
}

stop() {
	pkill udhcpd
}

status() {
	if pidof udhcpd | sed "s/$$\$//" | grep -q [0-9]
	then
		echo "running"
	else
		echo "stopped"
	fi
}
