#!/bin/sh /etc/rc.common

START=97

start() {
	local	reset
	local	timeout

	config_load watchdog
	config_get  reset   "watchdog" Reset	10
	config_get  timeout "watchdog" Timeout 	60
		
	[ -c /dev/watchdog ] && [ -x /sbin/watchdog ] && [ -x /bin/nice ] && \
    	/bin/nice -n -20 /sbin/watchdog -t $reset -T $timeout /dev/watchdog
}

stop() {
	killall -q watchdog 
}

status() {
	if pidof watchdog | sed "s/$$\$//" | grep -q [0-9] ; then
		echo "running"
	else
		echo "stopped"
	fi
}
