#!/bin/sh /etc/rc.common

START=97

start() {
	. /etc/config/watchdog.conf
	[ -c /dev/watchdog ] && [ -x /sbin/watchdog ] && [ -x /bin/nice ] && \
    	/bin/nice -n -20 /sbin/watchdog -t $WATCHDOG_TIMEOUT -T 300 /dev/watchdog
}

stop() {
	killall -q watchdog 
}

status() {
	if pidof watchdog | sed "s/$$\$//" | grep -q [0-9] ; then
		echo "running"
	else
		echo "stopped"
	fi
}
