#!/bin/sh /etc/rc.common

START=20

start() {
    killall -q hotplug2
    [ -x /sbin/hotplug2 ] && /sbin/hotplug2 --override --persistent \
            --set-worker /lib/hotplug2/worker_fork.so \
            --set-rules-file /etc/hotplug2.rules \
            --max-children 1 >/dev/null 2>&1 &

    # the coldplugging of network interfaces needs to happen later, so we do it manually here
    for iface in $(awk -F: '/:/ {print $1}' /proc/net/dev); do
        echo "IFACE : $iface"
        /usr/bin/env -i ACTION=add INTERFACE="$iface" /sbin/hotplug-call net
    done
}

