#!/bin/sh

git rm -rf openssh-7.1p1/Makefile
git rm -rf openssh-7.1p1/buildpkg.sh
git rm -rf openssh-7.1p1/config.h
git rm -rf openssh-7.1p1/config.log
git rm -rf openssh-7.1p1/config.status
git rm -rf openssh-7.1p1/moduli.5.out
git rm -rf openssh-7.1p1/moduli.out
git rm -rf openssh-7.1p1/openbsd-compat/Makefile
git rm -rf openssh-7.1p1/openbsd-compat/regress/Makefile
git rm -rf openssh-7.1p1/openssh.xml
git rm -rf openssh-7.1p1/opensshd.init
git rm -rf openssh-7.1p1/scp
git rm -rf openssh-7.1p1/scp.1.out
git rm -rf openssh-7.1p1/sftp
git rm -rf openssh-7.1p1/sftp-server
git rm -rf openssh-7.1p1/sftp-server.8.out
git rm -rf openssh-7.1p1/sftp.1.out
git rm -rf openssh-7.1p1/ssh
git rm -rf openssh-7.1p1/ssh-add
git rm -rf openssh-7.1p1/ssh-add.1.out
git rm -rf openssh-7.1p1/ssh-agent
git rm -rf openssh-7.1p1/ssh-agent.1.out
git rm -rf openssh-7.1p1/ssh-keygen
git rm -rf openssh-7.1p1/ssh-keygen.1.out
git rm -rf openssh-7.1p1/ssh-keyscan
git rm -rf openssh-7.1p1/ssh-keyscan.1.out
git rm -rf openssh-7.1p1/ssh-keysign
git rm -rf openssh-7.1p1/ssh-keysign.8.out
git rm -rf openssh-7.1p1/ssh-pkcs11-helper
git rm -rf openssh-7.1p1/ssh-pkcs11-helper.8.out
git rm -rf openssh-7.1p1/ssh.1.out
git rm -rf openssh-7.1p1/ssh_config.5.out
git rm -rf openssh-7.1p1/ssh_config.out
git rm -rf openssh-7.1p1/sshd
git rm -rf openssh-7.1p1/sshd.8.out
git rm -rf openssh-7.1p1/sshd_config.5.out
git rm -rf openssh-7.1p1/sshd_config.out
git rm -rf openssh-7.1p1/survey.sh
